name: im_mottu_mobile
description: "vrum vrum"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  dio_cache_interceptor: ^3.5.0
  shared_preferences: ^2.3.2
  crypto: ^3.0.5
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
